version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-env
    volumes:
      - ./:/usr/src/app
      - $HOME/.aws:/root/.aws
    ports:
      - 8092:80

  binary:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.aws:/root/.aws
    ports:
      - 8093:80

